### ISSUE TITLE
IndexOutOfBoundsException while adding screenshot for iOS

### ISSUE THREAD

**Issue by aakacenoks** [testdevlab/TestUI#50]
#### TestUI Version:
v1.2.2

#### Platform
App iOS

#### Steps
Given I set the configuration variable: `useAllure = true;`
When I run a test and `element.ShouldBe().visible();` fails
Then screenshot is taken and attached to allure report

#### Results
Exception is thrown and screenshot is not attached to allure report

#### Console log
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:657)
    at java.util.ArrayList.get(ArrayList.java:433)
    at testUI.Utils.WaitUntil.assertFunction(WaitUntil.java:33)
    at testUI.Utils.WaitUntil.waitUntilVisible(WaitUntil.java:90)
    at testUI.elements.ShouldBe.visible(ShouldBe.java:82)
    at stepDefinitions.HomePageSteps.iPressBuyNewButton(HomePageSteps.java:236)
```

**Comment by alvarolaserna** [comment]
Fixed in v1.2.3
